airlock metrics
vostok/vostok.airlock.client pull request #4
Opened 2018-02-27 05:31 UTC by trurl123

2018-02-27 05:32 UTC, trurl123 commented
see https://github.com/vostok/vostok.airlock.client/issues/1

2018-02-28 07:08 UTC, spaceorc requested changes

2018-02-28 07:08 UTC, spaceorc commented on Vostok.Airlock.Client/AirlockConfig.cs
> +        public bool EnableMetrics { get; set; } = false;
Это мы договорились так, что метрики по умолчанию отключены? Вроде, это странно...

2018-02-28 07:08 UTC, spaceorc commented on Vostok.Airlock.Client/AirlockClientFactory.cs
> +        public static IAirlockClient CreateAirlockClient(AirlockConfig airlockConfig, ILog log, IMetricScope metricScope = null)
По факту, в результате лимит на память не исполняется (исполняется умноженный на паралеллизм). Кажется, это неправильно...

2018-02-28 07:08 UTC, spaceorc commented on Vostok.Airlock.Client/AirlockClientFactory.cs
> +    public static class AirlockClientFactory
Мне вообще не нравится фабрика. Это всегда лишняя сложность в интерфейсе библиотек. Если этого можно избежать - это хорошо. В данном случае, мне кажется, надо выделить что-то вроде Implementor-а, и оставить один публичный класс AirlockClient, который сам разберется с параллельностью, и создаст столько потоков и имплементоров, сколько надо. Учтет параллелизм корректно и все такое.

2018-02-28 07:08 UTC, spaceorc commented on Vostok.Airlock.Client/AirlockClient.cs
> +        public AirlockClient(AirlockConfig config, ILog log = null, AirlockClientCounters counters = null)
Ну, и, если сделать без всяких фабрик, то и этого параметра странного будет не нужно...

2021-08-16 12:40 UTC, closed without merging